"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

type Settlement = {
  _id: string;
  settlementId: string;
  merchantEmail: string;
  totalSuccessAmount: number;
  totalRefundedAmount: number;
  totalChargebackLostAmount: number;
  platformFee: number;
  netSettlementAmount: number;
  currency: string;
  status: string;
  note: string;
  paidAt: string | null;
  createdAt: string;
};

export default function AdminSettlementsPage() {
  const [settlements, setSettlements] = useState<Settlement[]>([]);
  const [merchantEmail, setMerchantEmail] = useState("abc@gmail.com");
  const [note, setNote] = useState("Settlement generated by admin");
  const [loading, setLoading] = useState(true);
  const [creating, setCreating] = useState(false);
  const [savingId, setSavingId] = useState("");
  const [message, setMessage] = useState("");

  async function loadSettlements() {
    try {
      setLoading(true);

      const response = await fetch("/api/settlements", {
        cache: "no-store",
      });

      const data = await response.json();

      if (data.success) {
        setSettlements(data.settlements || []);
      }
    } catch (error) {
      console.error("Failed to load settlements:", error);
    } finally {
      setLoading(false);
    }
  }

  async function generateSettlement(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setCreating(true);
    setMessage("");

    try {
      const response = await fetch("/api/settlements", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          merchantEmail,
          note,
        }),
      });

      const data = await response.json();

      if (!response.ok || !data.success) {
        setMessage(data.message || "Failed to generate settlement");
        return;
      }

      setMessage("Settlement generated successfully.");
      await loadSettlements();
    } catch {
      setMessage("Something went wrong while generating settlement.");
    } finally {
      setCreating(false);
    }
  }

  async function updateSettlement(settlementId: string, status: "pending" | "processing" | "paid") {
    try {
      setSavingId(settlementId);

      const response = await fetch(`/api/settlements/${settlementId}`, {
        method: "PATCH",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          status,
          note,
        }),
      });

      const data = await response.json();

      if (!response.ok || !data.success) {
        alert(data.message || "Failed to update settlement");
        return;
      }

      await loadSettlements();
    } catch {
      alert("Something went wrong while updating settlement.");
    } finally {
      setSavingId("");
    }
  }

  useEffect(() => {
    loadSettlements();
  }, []);

  const pendingSettlements = settlements.filter((settlement) => settlement.status === "pending").length;
  const processingSettlements = settlements.filter((settlement) => settlement.status === "processing").length;
  const paidSettlements = settlements.filter((settlement) => settlement.status === "paid").length;

  const totalNetAmount = settlements.reduce((sum, settlement) => {
    return sum + Number(settlement.netSettlementAmount || 0);
  }, 0);

  return (
    <main>
      <div className="mx-auto max-w-7xl">
        <div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-center">
          <div>
            <p className="mb-2 text-sm font-bold uppercase tracking-[0.3em] text-blue-600">
              Wpay Admin
            </p>
            <h1 className="text-4xl font-black">Settlements</h1>
            <p className="mt-2 text-gray-600">
              Generate and manage merchant settlements from PostgreSQL transactions.
            </p>
          </div>

          <div className="flex flex-wrap gap-3">
            <button
              onClick={loadSettlements}
              className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold hover:bg-blue-700"
            >
              Refresh
            </button>

            <Link
              href="/admin/transactions"
              className="rounded-xl border border-gray-200 px-5 py-3 text-sm font-bold hover:bg-gray-50"
            >
              Transactions
            </Link>

            <Link
              href="/admin/dashboard"
              className="rounded-xl border border-gray-200 px-5 py-3 text-sm font-bold hover:bg-gray-50"
            >
              Dashboard
            </Link>
          </div>
        </div>

        <div className="grid gap-4 md:grid-cols-4">
          <div className="rounded-2xl border border-gray-200 bg-white p-5">
            <p className="text-sm text-gray-600">Total Settlements</p>
            <p className="mt-2 text-3xl font-black">{settlements.length}</p>
          </div>

          <div className="rounded-2xl border border-gray-200 bg-white p-5">
            <p className="text-sm text-gray-600">Pending</p>
            <p className="mt-2 text-3xl font-black text-amber-600">{pendingSettlements}</p>
          </div>

          <div className="rounded-2xl border border-gray-200 bg-white p-5">
            <p className="text-sm text-gray-600">Processing</p>
            <p className="mt-2 text-3xl font-black text-blue-600">{processingSettlements}</p>
          </div>

          <div className="rounded-2xl border border-gray-200 bg-white p-5">
            <p className="text-sm text-gray-600">Paid</p>
            <p className="mt-2 text-3xl font-black text-emerald-600">{paidSettlements}</p>
          </div>
        </div>

        <section className="mt-8 rounded-3xl border border-gray-200 bg-white p-6">
          <h2 className="text-2xl font-black">Generate Settlement</h2>
          <p className="mt-2 text-sm text-gray-600">
            Platform fee is calculated at 2% of successful transaction volume.
          </p>

          <form onSubmit={generateSettlement} className="mt-6 grid gap-4 md:grid-cols-[1fr_1fr_auto] md:items-end">
            <div>
              <label className="mb-2 block text-sm font-bold text-gray-700">
                Merchant Email
              </label>
              <input
                value={merchantEmail}
                onChange={(event) => setMerchantEmail(event.target.value)}
                className="w-full rounded-xl border border-gray-200 bg-white px-4 py-3 text-gray-900 outline-none focus:border-blue-500"
                required
              />
            </div>

            <div>
              <label className="mb-2 block text-sm font-bold text-gray-700">
                Note
              </label>
              <input
                value={note}
                onChange={(event) => setNote(event.target.value)}
                className="w-full rounded-xl border border-gray-200 bg-white px-4 py-3 text-gray-900 outline-none focus:border-blue-500"
              />
            </div>

            <button
              type="submit"
              disabled={creating}
              className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold hover:bg-blue-700 disabled:opacity-60"
            >
              {creating ? "Generating..." : "Generate"}
            </button>
          </form>

          {message ? (
            <div className="mt-4 rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm font-semibold text-blue-100">
              {message}
            </div>
          ) : null}
        </section>

        <section className="mt-8 overflow-hidden rounded-3xl border border-gray-200 bg-white">
          <div className="border-b border-gray-200 p-5">
            <h2 className="text-xl font-black">Settlement Records</h2>
            <p className="mt-1 text-sm text-gray-600">
              Total net settlement amount: INR {totalNetAmount}
            </p>
          </div>

          {loading ? (
            <div className="p-8 text-gray-700">Loading settlements...</div>
          ) : settlements.length === 0 ? (
            <div className="p-8 text-gray-700">
              No settlements found. Generate one settlement first.
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full min-w-[1350px] text-left text-sm">
                <thead className="bg-white text-gray-700">
                  <tr>
                    <th className="px-5 py-4">Settlement</th>
                    <th className="px-5 py-4">Merchant</th>
                    <th className="px-5 py-4">Success</th>
                    <th className="px-5 py-4">Refunded</th>
                    <th className="px-5 py-4">Chargeback Lost</th>
                    <th className="px-5 py-4">Fee</th>
                    <th className="px-5 py-4">Net Payable</th>
                    <th className="px-5 py-4">Status</th>
                    <th className="px-5 py-4">Actions</th>
                  </tr>
                </thead>

                <tbody>
                  {settlements.map((settlement) => (
                    <tr key={settlement._id} className="border-t border-gray-200">
                      <td className="px-5 py-4">
                        <p className="font-bold">{settlement.settlementId}</p>
                        <p className="mt-1 text-xs text-gray-600">
                          {new Date(settlement.createdAt).toLocaleString()}
                        </p>
                      </td>

                      <td className="px-5 py-4 text-gray-700">
                        {settlement.merchantEmail}
                      </td>

                      <td className="px-5 py-4 font-bold">
                        {settlement.currency} {settlement.totalSuccessAmount}
                      </td>

                      <td className="px-5 py-4 font-bold text-red-600">
                        {settlement.currency} {settlement.totalRefundedAmount}
                      </td>

                      <td className="px-5 py-4 font-bold text-orange-300">
                        {settlement.currency} {settlement.totalChargebackLostAmount || 0}
                      </td>

                      <td className="px-5 py-4 font-bold text-amber-600">
                        {settlement.currency} {settlement.platformFee}
                      </td>

                      <td className="px-5 py-4 text-lg font-black text-emerald-600">
                        {settlement.currency} {settlement.netSettlementAmount}
                      </td>

                      <td className="px-5 py-4">
                        <span
                          className={`rounded-full px-3 py-1 text-xs font-bold ${
                            settlement.status === "paid"
                              ? "bg-emerald-100 text-emerald-600"
                              : settlement.status === "processing"
                                ? "bg-blue-50 text-blue-600"
                                : "bg-amber-50 text-amber-600"
                          }`}
                        >
                          {settlement.status}
                        </span>
                      </td>

                      <td className="px-5 py-4">
                        <div className="flex flex-wrap gap-2">
                          <button
                            disabled={savingId === settlement.settlementId}
                            onClick={() => updateSettlement(settlement.settlementId, "processing")}
                            className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-bold hover:bg-blue-700 disabled:opacity-50"
                          >
                            Processing
                          </button>

                          <button
                            disabled={savingId === settlement.settlementId}
                            onClick={() => updateSettlement(settlement.settlementId, "paid")}
                            className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold hover:bg-emerald-700 disabled:opacity-50"
                          >
                            Mark Paid
                          </button>
                        </div>

                        {savingId === settlement.settlementId ? (
                          <p className="mt-2 text-xs text-blue-600">Saving...</p>
                        ) : null}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </section>
      </div>
    </main>
  );
}

